"use client";

import { useEffect, useId, useState } from "react";

type MermaidWidgetProps = {
  code: string;
};

export function MermaidWidget({ code }: MermaidWidgetProps) {
  const rawId = useId();
  // useId can produce colons; mermaid requires a valid HTML id
  const safeId = `mermaid-${rawId.replace(/[^a-zA-Z0-9-]/g, "")}`;

  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;

        // Detect dark mode from the <html> element class added by next-themes
        const isDark =
          typeof document !== "undefined" &&
          document.documentElement.classList.contains("dark");

        mermaid.initialize({
          startOnLoad: false,
          theme: isDark ? "dark" : "default",
        });

        const { svg: rendered } = await mermaid.render(safeId, code.trim());
        if (!cancelled) setSvg(rendered);
      } catch (err) {
        if (!cancelled) setError(String(err));
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code, safeId]);

  if (error) {
    return (
      <div className="not-prose my-6 rounded border border-dashed border-rose-300 p-3 font-mono text-sm text-rose-500 dark:border-rose-700">
        Mermaid parse error: {error}
      </div>
    );
  }

  if (!svg) {
    return (
      <div className="not-prose my-6 flex items-center justify-center rounded border border-slate-200 py-10 text-sm text-slate-400 dark:border-slate-700">
        図を描画中…
      </div>
    );
  }

  return (
    <div
      className="not-prose my-6 overflow-x-auto rounded border border-slate-200 p-4 dark:border-slate-700 [&_svg]:mx-auto [&_svg]:block [&_svg]:max-w-full"
      // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG is generated by mermaid from trusted markdown source
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
